# Generated by Django 3.1.6 on 2021-02-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=100)),
                ('duracao', models.TextField(max_length=100)),
                ('spotify', models.CharField(choices=[('SIM', 'Já foi publicado'), ('NÃO', 'Não foi publicado')], max_length=3)),
                ('youtube', models.CharField(choices=[('SIM', 'Já foi publicado'), ('NÃO', 'Não foi publicado')], max_length=3)),
                ('artista', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'musica',
            },
        ),
    ]
